language: python
cache: pip
python: 3.7-dev
install:
- pip install -r requirements.txt
- pip install flake8
script:
- flake8 --show-source tapioca
- python -m unittest discover
notifications:
  email: false
