language: go
cache:
  pip: true
  directories:
  - $HOME/protoc
go: "1.11"
env:
  global:
    - PROTO_VERSION="3.6.1"
before_install:
- bash install_protobuf.sh $PROTO_VERSION
install:
- bash -c "shopt -s globstar; $HOME/protoc/bin/protoc --proto_path=$HOME/protoc/include --proto_path=$(pwd) --go_out=$(pwd) **/*.proto"
- go get -t ./...
script:
- go test -v ./...
notifications:
  email: false
