language: go
cache:
  pip: true
  directories:
  - $HOME/protoc
go: "1.11"
env:
  global:
    - PROTO_VERSION="3.6.1"
before_install:
- bash ./scripts/install_protobuf.sh $PROTO_VERSION
- curl -sfL https://install.goreleaser.com/github.com/golangci/golangci-lint.sh | sh -s v1.12
- go get -u github.com/golang/protobuf/protoc-gen-go
install:
  - bash -c "shopt -s globstar; $HOME/protoc/bin/protoc --proto_path=$HOME/protoc/include --proto_path=$(pwd) --go_out=plugins=grpc:$(pwd) **/*.proto"
- go get -t ./...
script:
- ./bin/golangci-lint run
- go test -v ./...
notifications:
  email: false
