language: python
cache:
  pip: true
  directories:
  - $HOME/protoc
python: 3.7-dev
env:
  global:
    - PROTO_VERSION="3.6.1"
before_install:
- bash install_protobuf.sh $PROTO_VERSION
install:
- pip install -r requirements.txt
- pip install flake8
script:
- flake8 --show-source tapioca
- bash -c "shopt -s globstar; $HOME/protoc/bin/protoc --proto_path=$HOME/protoc/include --proto_path=$(pwd) --python_out=$(pwd) **/*.proto"
- python -m unittest discover
notifications:
  email: false
