// Code generated by protoc-gen-go. DO NOT EDIT.
// source: pkg/core/data.proto

package core

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	duration "github.com/golang/protobuf/ptypes/duration"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type ProjectConfig struct {
	Id            *uint32                  `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	DefaultBranch *uint32                  `protobuf:"varint,2,opt,name=default_branch,json=defaultBranch" json:"default_branch,omitempty"`
	Branches      map[uint32]*BranchConfig `protobuf:"bytes,3,rep,name=branches" json:"branches,omitempty" protobuf_key:"varint,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// Required: Platform specific launch options. Map keys are Platform values.
	// These values are overriden by branch specific options if they are present.
	LaunchOptions           map[uint32]*LaunchOptions `protobuf:"bytes,4,rep,name=launch_options,json=launchOptions" json:"launch_options,omitempty" protobuf_key:"varint,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	GarbageCollectionPolicy *GarbageCollectionPolicy  `protobuf:"bytes,5,opt,name=garbage_collection_policy,json=garbageCollectionPolicy" json:"garbage_collection_policy,omitempty"`
	// Required: the URL prefix to download objects from.
	BlockStoragePrefix   *string  `protobuf:"bytes,6,opt,name=block_storage_prefix,json=blockStoragePrefix" json:"block_storage_prefix,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ProjectConfig) Reset()         { *m = ProjectConfig{} }
func (m *ProjectConfig) String() string { return proto.CompactTextString(m) }
func (*ProjectConfig) ProtoMessage()    {}
func (*ProjectConfig) Descriptor() ([]byte, []int) {
	return fileDescriptor_5271f2b505a1559d, []int{0}
}

func (m *ProjectConfig) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProjectConfig.Unmarshal(m, b)
}
func (m *ProjectConfig) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProjectConfig.Marshal(b, m, deterministic)
}
func (m *ProjectConfig) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProjectConfig.Merge(m, src)
}
func (m *ProjectConfig) XXX_Size() int {
	return xxx_messageInfo_ProjectConfig.Size(m)
}
func (m *ProjectConfig) XXX_DiscardUnknown() {
	xxx_messageInfo_ProjectConfig.DiscardUnknown(m)
}

var xxx_messageInfo_ProjectConfig proto.InternalMessageInfo

func (m *ProjectConfig) GetId() uint32 {
	if m != nil && m.Id != nil {
		return *m.Id
	}
	return 0
}

func (m *ProjectConfig) GetDefaultBranch() uint32 {
	if m != nil && m.DefaultBranch != nil {
		return *m.DefaultBranch
	}
	return 0
}

func (m *ProjectConfig) GetBranches() map[uint32]*BranchConfig {
	if m != nil {
		return m.Branches
	}
	return nil
}

func (m *ProjectConfig) GetLaunchOptions() map[uint32]*LaunchOptions {
	if m != nil {
		return m.LaunchOptions
	}
	return nil
}

func (m *ProjectConfig) GetGarbageCollectionPolicy() *GarbageCollectionPolicy {
	if m != nil {
		return m.GarbageCollectionPolicy
	}
	return nil
}

func (m *ProjectConfig) GetBlockStoragePrefix() string {
	if m != nil && m.BlockStoragePrefix != nil {
		return *m.BlockStoragePrefix
	}
	return ""
}

// Determines the build purge policy of a project.
//
// Purged builds do not have their data deleted, but will have the refrence
// originating from the build deleted.
type GarbageCollectionPolicy struct {
	// Builds older than a given retention duration will be purged.
	//
	// If unset, builds are indefinitely until manually purged.
	//
	// Exception: At least one build per branch/target combination will be
	// retained of what this is set to.
	RetentionDuration *duration.Duration `protobuf:"bytes,1,opt,name=retention_duration,json=retentionDuration" json:"retention_duration,omitempty"`
	// The number of builds to retain per branch/target combionation. As new
	// builds are pushed.
	//
	// If not set, the value is assumed to be 1.
	RetainedBuilds       *uint64  `protobuf:"varint,2,opt,name=retained_builds,json=retainedBuilds" json:"retained_builds,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GarbageCollectionPolicy) Reset()         { *m = GarbageCollectionPolicy{} }
func (m *GarbageCollectionPolicy) String() string { return proto.CompactTextString(m) }
func (*GarbageCollectionPolicy) ProtoMessage()    {}
func (*GarbageCollectionPolicy) Descriptor() ([]byte, []int) {
	return fileDescriptor_5271f2b505a1559d, []int{1}
}

func (m *GarbageCollectionPolicy) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GarbageCollectionPolicy.Unmarshal(m, b)
}
func (m *GarbageCollectionPolicy) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GarbageCollectionPolicy.Marshal(b, m, deterministic)
}
func (m *GarbageCollectionPolicy) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GarbageCollectionPolicy.Merge(m, src)
}
func (m *GarbageCollectionPolicy) XXX_Size() int {
	return xxx_messageInfo_GarbageCollectionPolicy.Size(m)
}
func (m *GarbageCollectionPolicy) XXX_DiscardUnknown() {
	xxx_messageInfo_GarbageCollectionPolicy.DiscardUnknown(m)
}

var xxx_messageInfo_GarbageCollectionPolicy proto.InternalMessageInfo

func (m *GarbageCollectionPolicy) GetRetentionDuration() *duration.Duration {
	if m != nil {
		return m.RetentionDuration
	}
	return nil
}

func (m *GarbageCollectionPolicy) GetRetainedBuilds() uint64 {
	if m != nil && m.RetainedBuilds != nil {
		return *m.RetainedBuilds
	}
	return 0
}

type LaunchOptions struct {
	// The path of game executable that is to be launched, relative to the root
	// directory of the build.
	//
	// Note: path is seperated by '/' path seperator.
	Executable *string `protobuf:"bytes,1,opt,name=executable" json:"executable,omitempty"`
	// The additional command line flags used when launching on a platform.
	LaunchFlags          []string `protobuf:"bytes,2,rep,name=launch_flags,json=launchFlags" json:"launch_flags,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LaunchOptions) Reset()         { *m = LaunchOptions{} }
func (m *LaunchOptions) String() string { return proto.CompactTextString(m) }
func (*LaunchOptions) ProtoMessage()    {}
func (*LaunchOptions) Descriptor() ([]byte, []int) {
	return fileDescriptor_5271f2b505a1559d, []int{2}
}

func (m *LaunchOptions) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LaunchOptions.Unmarshal(m, b)
}
func (m *LaunchOptions) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LaunchOptions.Marshal(b, m, deterministic)
}
func (m *LaunchOptions) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LaunchOptions.Merge(m, src)
}
func (m *LaunchOptions) XXX_Size() int {
	return xxx_messageInfo_LaunchOptions.Size(m)
}
func (m *LaunchOptions) XXX_DiscardUnknown() {
	xxx_messageInfo_LaunchOptions.DiscardUnknown(m)
}

var xxx_messageInfo_LaunchOptions proto.InternalMessageInfo

func (m *LaunchOptions) GetExecutable() string {
	if m != nil && m.Executable != nil {
		return *m.Executable
	}
	return ""
}

func (m *LaunchOptions) GetLaunchFlags() []string {
	if m != nil {
		return m.LaunchFlags
	}
	return nil
}

// ID: 8 bytes:
//     {4-byte Project ID} +
//     {4-byte branch name fingerprint}
type BranchConfig struct {
	ProjectId *uint32 `protobuf:"varint,1,opt,name=project_id,json=projectId" json:"project_id,omitempty"`
	Id        *uint32 `protobuf:"varint,2,opt,name=id" json:"id,omitempty"`
	// Source control branch name.
	Name *string `protobuf:"bytes,3,opt,name=name" json:"name,omitempty"`
	// Optional: Human facing display name for the branch
	DisplayName *string `protobuf:"bytes,4,opt,name=display_name,json=displayName" json:"display_name,omitempty"`
	// Optional: Platform specific launch options. Map keys are Platform values.
	// Overrides project wide launch options when provided.
	LaunchOptions        map[uint32]*LaunchOptions `protobuf:"bytes,5,rep,name=launch_options,json=launchOptions" json:"launch_options,omitempty" protobuf_key:"varint,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	XXX_NoUnkeyedLiteral struct{}                  `json:"-"`
	XXX_unrecognized     []byte                    `json:"-"`
	XXX_sizecache        int32                     `json:"-"`
}

func (m *BranchConfig) Reset()         { *m = BranchConfig{} }
func (m *BranchConfig) String() string { return proto.CompactTextString(m) }
func (*BranchConfig) ProtoMessage()    {}
func (*BranchConfig) Descriptor() ([]byte, []int) {
	return fileDescriptor_5271f2b505a1559d, []int{3}
}

func (m *BranchConfig) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BranchConfig.Unmarshal(m, b)
}
func (m *BranchConfig) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BranchConfig.Marshal(b, m, deterministic)
}
func (m *BranchConfig) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BranchConfig.Merge(m, src)
}
func (m *BranchConfig) XXX_Size() int {
	return xxx_messageInfo_BranchConfig.Size(m)
}
func (m *BranchConfig) XXX_DiscardUnknown() {
	xxx_messageInfo_BranchConfig.DiscardUnknown(m)
}

var xxx_messageInfo_BranchConfig proto.InternalMessageInfo

func (m *BranchConfig) GetProjectId() uint32 {
	if m != nil && m.ProjectId != nil {
		return *m.ProjectId
	}
	return 0
}

func (m *BranchConfig) GetId() uint32 {
	if m != nil && m.Id != nil {
		return *m.Id
	}
	return 0
}

func (m *BranchConfig) GetName() string {
	if m != nil && m.Name != nil {
		return *m.Name
	}
	return ""
}

func (m *BranchConfig) GetDisplayName() string {
	if m != nil && m.DisplayName != nil {
		return *m.DisplayName
	}
	return ""
}

func (m *BranchConfig) GetLaunchOptions() map[uint32]*LaunchOptions {
	if m != nil {
		return m.LaunchOptions
	}
	return nil
}

type BuildProto struct {
	// ID: 14 bytes:
	//     {8-byte Branch ID} +
	//     {4-byte truncated SHA-1 of commit}
	//     {2-byte target} +
	Id []byte `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	// The build manifest
	Manifest *ManifestProto       `protobuf:"bytes,2,opt,name=manifest" json:"manifest,omitempty"`
	Metadata *BuildProto_Metadata `protobuf:"bytes,3,opt,name=metadata" json:"metadata,omitempty"`
	// Information on how to launch the build.
	LaunchOptions        *LaunchOptions `protobuf:"bytes,4,opt,name=launch_options,json=launchOptions" json:"launch_options,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *BuildProto) Reset()         { *m = BuildProto{} }
func (m *BuildProto) String() string { return proto.CompactTextString(m) }
func (*BuildProto) ProtoMessage()    {}
func (*BuildProto) Descriptor() ([]byte, []int) {
	return fileDescriptor_5271f2b505a1559d, []int{4}
}

func (m *BuildProto) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BuildProto.Unmarshal(m, b)
}
func (m *BuildProto) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BuildProto.Marshal(b, m, deterministic)
}
func (m *BuildProto) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BuildProto.Merge(m, src)
}
func (m *BuildProto) XXX_Size() int {
	return xxx_messageInfo_BuildProto.Size(m)
}
func (m *BuildProto) XXX_DiscardUnknown() {
	xxx_messageInfo_BuildProto.DiscardUnknown(m)
}

var xxx_messageInfo_BuildProto proto.InternalMessageInfo

func (m *BuildProto) GetId() []byte {
	if m != nil {
		return m.Id
	}
	return nil
}

func (m *BuildProto) GetManifest() *ManifestProto {
	if m != nil {
		return m.Manifest
	}
	return nil
}

func (m *BuildProto) GetMetadata() *BuildProto_Metadata {
	if m != nil {
		return m.Metadata
	}
	return nil
}

func (m *BuildProto) GetLaunchOptions() *LaunchOptions {
	if m != nil {
		return m.LaunchOptions
	}
	return nil
}

type BuildProto_Metadata struct {
	// Required: The source control commit hash.
	SourceCommit []byte `protobuf:"bytes,1,opt,name=source_commit,json=sourceCommit" json:"source_commit,omitempty"`
	// Reqired: The timestamp the build was created at.
	BuildTimestamp *timestamp.Timestamp `protobuf:"bytes,2,opt,name=build_timestamp,json=buildTimestamp" json:"build_timestamp,omitempty"`
	// Required: The target platform for the build
	Target               *Target  `protobuf:"varint,3,opt,name=target,enum=tapioca.Target" json:"target,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BuildProto_Metadata) Reset()         { *m = BuildProto_Metadata{} }
func (m *BuildProto_Metadata) String() string { return proto.CompactTextString(m) }
func (*BuildProto_Metadata) ProtoMessage()    {}
func (*BuildProto_Metadata) Descriptor() ([]byte, []int) {
	return fileDescriptor_5271f2b505a1559d, []int{4, 0}
}

func (m *BuildProto_Metadata) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BuildProto_Metadata.Unmarshal(m, b)
}
func (m *BuildProto_Metadata) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BuildProto_Metadata.Marshal(b, m, deterministic)
}
func (m *BuildProto_Metadata) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BuildProto_Metadata.Merge(m, src)
}
func (m *BuildProto_Metadata) XXX_Size() int {
	return xxx_messageInfo_BuildProto_Metadata.Size(m)
}
func (m *BuildProto_Metadata) XXX_DiscardUnknown() {
	xxx_messageInfo_BuildProto_Metadata.DiscardUnknown(m)
}

var xxx_messageInfo_BuildProto_Metadata proto.InternalMessageInfo

func (m *BuildProto_Metadata) GetSourceCommit() []byte {
	if m != nil {
		return m.SourceCommit
	}
	return nil
}

func (m *BuildProto_Metadata) GetBuildTimestamp() *timestamp.Timestamp {
	if m != nil {
		return m.BuildTimestamp
	}
	return nil
}

func (m *BuildProto_Metadata) GetTarget() Target {
	if m != nil && m.Target != nil {
		return *m.Target
	}
	return Target_Windows_x64
}

// ID: 78 bytes:
//     {64-byte block SHA-512} +
//     {14-byte block build hash}
type BlockInfo struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BlockInfo) Reset()         { *m = BlockInfo{} }
func (m *BlockInfo) String() string { return proto.CompactTextString(m) }
func (*BlockInfo) ProtoMessage()    {}
func (*BlockInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_5271f2b505a1559d, []int{5}
}

func (m *BlockInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BlockInfo.Unmarshal(m, b)
}
func (m *BlockInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BlockInfo.Marshal(b, m, deterministic)
}
func (m *BlockInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BlockInfo.Merge(m, src)
}
func (m *BlockInfo) XXX_Size() int {
	return xxx_messageInfo_BlockInfo.Size(m)
}
func (m *BlockInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_BlockInfo.DiscardUnknown(m)
}

var xxx_messageInfo_BlockInfo proto.InternalMessageInfo

func init() {
	proto.RegisterType((*ProjectConfig)(nil), "ProjectConfig")
	proto.RegisterMapType((map[uint32]*BranchConfig)(nil), "ProjectConfig.BranchesEntry")
	proto.RegisterMapType((map[uint32]*LaunchOptions)(nil), "ProjectConfig.LaunchOptionsEntry")
	proto.RegisterType((*GarbageCollectionPolicy)(nil), "GarbageCollectionPolicy")
	proto.RegisterType((*LaunchOptions)(nil), "LaunchOptions")
	proto.RegisterType((*BranchConfig)(nil), "BranchConfig")
	proto.RegisterMapType((map[uint32]*LaunchOptions)(nil), "BranchConfig.LaunchOptionsEntry")
	proto.RegisterType((*BuildProto)(nil), "BuildProto")
	proto.RegisterType((*BuildProto_Metadata)(nil), "BuildProto.Metadata")
	proto.RegisterType((*BlockInfo)(nil), "BlockInfo")
}

func init() { proto.RegisterFile("pkg/core/data.proto", fileDescriptor_5271f2b505a1559d) }

var fileDescriptor_5271f2b505a1559d = []byte{
	// 674 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x54, 0xdd, 0x6e, 0xd3, 0x30,
	0x14, 0x56, 0x7f, 0x36, 0xb5, 0x27, 0x4d, 0x07, 0x66, 0x62, 0x59, 0x05, 0xa3, 0xeb, 0x40, 0xeb,
	0x55, 0x3a, 0x45, 0x42, 0x9a, 0xb8, 0x6c, 0x81, 0x6d, 0x88, 0x41, 0x65, 0x76, 0xc5, 0x4d, 0xe4,
	0x26, 0x4e, 0x16, 0x96, 0xc4, 0x51, 0xe2, 0xa0, 0xf5, 0x1d, 0x90, 0x78, 0x02, 0x1e, 0x8c, 0xb7,
	0xe0, 0x11, 0x50, 0x4e, 0x9c, 0xd0, 0x6e, 0x45, 0x5c, 0x71, 0x97, 0x7c, 0xdf, 0xe7, 0x63, 0x9f,
	0xcf, 0x9f, 0x0f, 0x3c, 0x4a, 0x6e, 0xfc, 0x89, 0x23, 0x52, 0x3e, 0x71, 0x99, 0x64, 0x66, 0x92,
	0x0a, 0x29, 0x06, 0x7b, 0x35, 0x18, 0xb1, 0x38, 0xf0, 0x78, 0x26, 0x15, 0xf1, 0xcc, 0x17, 0xc2,
	0x0f, 0xf9, 0x04, 0xff, 0x16, 0xb9, 0x37, 0x91, 0x41, 0xc4, 0x33, 0xc9, 0xa2, 0x44, 0x09, 0x0e,
	0xee, 0x0a, 0xdc, 0x3c, 0x65, 0x32, 0x10, 0x71, 0xc9, 0x8f, 0x7e, 0xb5, 0x40, 0x9f, 0xa7, 0xe2,
	0x0b, 0x77, 0xe4, 0x4c, 0xc4, 0x5e, 0xe0, 0x93, 0x3e, 0x34, 0x03, 0xd7, 0x68, 0x0c, 0x1b, 0x63,
	0x9d, 0x36, 0x03, 0x97, 0xbc, 0x80, 0xbe, 0xcb, 0x3d, 0x96, 0x87, 0xd2, 0x5e, 0xa4, 0x2c, 0x76,
	0xae, 0x8d, 0x26, 0x72, 0xba, 0x42, 0xa7, 0x08, 0x92, 0x53, 0xe8, 0x94, 0x34, 0xcf, 0x8c, 0xd6,
	0xb0, 0x35, 0xd6, 0xac, 0x27, 0xe6, 0x5a, 0x61, 0x73, 0xaa, 0xe8, 0x37, 0xb1, 0x4c, 0x97, 0xb4,
	0x56, 0x93, 0x73, 0xe8, 0x87, 0x2c, 0x8f, 0x9d, 0x6b, 0x5b, 0x24, 0xc5, 0xc9, 0x32, 0xa3, 0x8d,
	0xeb, 0x0f, 0xef, 0xac, 0x7f, 0x8f, 0xa2, 0x8f, 0xa5, 0xa6, 0x2c, 0xa2, 0x87, 0xab, 0x18, 0xb9,
	0x82, 0x7d, 0x9f, 0xa5, 0x0b, 0xe6, 0x73, 0xdb, 0x11, 0x61, 0xc8, 0x9d, 0x02, 0xb6, 0x13, 0x11,
	0x06, 0xce, 0xd2, 0xd8, 0x1a, 0x36, 0xc6, 0x9a, 0x65, 0x98, 0x67, 0xa5, 0x62, 0x56, 0x0b, 0xe6,
	0xc8, 0xd3, 0x3d, 0x7f, 0x33, 0x41, 0x4e, 0x60, 0x77, 0x11, 0x0a, 0xe7, 0xc6, 0xce, 0xa4, 0x48,
	0x8b, 0xda, 0x49, 0xca, 0xbd, 0xe0, 0xd6, 0xd8, 0x1e, 0x36, 0xc6, 0x5d, 0x4a, 0x90, 0xfb, 0x54,
	0x52, 0x73, 0x64, 0x06, 0xef, 0x40, 0x5f, 0x6b, 0x96, 0x3c, 0x80, 0xd6, 0x0d, 0x5f, 0x2a, 0x53,
	0x8b, 0x4f, 0x72, 0x04, 0x5b, 0x5f, 0x59, 0x98, 0x73, 0x34, 0x53, 0xb3, 0x74, 0xe5, 0x4e, 0xd9,
	0x2a, 0x2d, 0xb9, 0x57, 0xcd, 0xd3, 0xc6, 0x60, 0x0e, 0xe4, 0x7e, 0xe3, 0x1b, 0x0a, 0x3e, 0x5f,
	0x2f, 0xd8, 0x5f, 0xb7, 0x6b, 0xa5, 0xe2, 0xe8, 0x5b, 0x03, 0xf6, 0xfe, 0x62, 0x02, 0x39, 0x07,
	0x92, 0x72, 0xc9, 0x63, 0x34, 0xae, 0x8a, 0x0a, 0x6e, 0xa3, 0x59, 0xfb, 0x66, 0x99, 0x25, 0xb3,
	0xca, 0x92, 0xf9, 0x5a, 0x09, 0xe8, 0xc3, 0x7a, 0x51, 0x05, 0x91, 0x63, 0xd8, 0x49, 0xb9, 0x64,
	0x41, 0xcc, 0x5d, 0x7b, 0x91, 0x07, 0xa1, 0x9b, 0xe1, 0xc9, 0xda, 0xb4, 0x5f, 0xc1, 0x53, 0x44,
	0x47, 0x14, 0xf4, 0xb5, 0xa3, 0x92, 0x03, 0x00, 0x7e, 0xcb, 0x9d, 0x5c, 0xb2, 0x45, 0xc8, 0x71,
	0xef, 0x2e, 0x5d, 0x41, 0xc8, 0x21, 0xf4, 0x54, 0x5e, 0xbc, 0x90, 0xf9, 0x45, 0xd9, 0xd6, 0xb8,
	0x4b, 0xb5, 0x12, 0x7b, 0x5b, 0x40, 0xa3, 0xef, 0x4d, 0xe8, 0xad, 0x1a, 0x4a, 0x9e, 0x02, 0x24,
	0x65, 0x98, 0xec, 0x3a, 0xdc, 0x5d, 0x85, 0x5c, 0xb8, 0x2a, 0xf3, 0xcd, 0x3a, 0xf3, 0x04, 0xda,
	0x31, 0x8b, 0xb8, 0xd1, 0xc2, 0xcd, 0xf1, 0xbb, 0xd8, 0xd6, 0x0d, 0xb2, 0x24, 0x64, 0x4b, 0x1b,
	0xb9, 0x36, 0x72, 0x9a, 0xc2, 0x3e, 0x14, 0x92, 0xb3, 0x7b, 0x49, 0xde, 0xc2, 0x24, 0x0f, 0xd7,
	0x6e, 0xf7, 0xdf, 0x41, 0xfe, 0x0f, 0x97, 0xfe, 0xb3, 0x09, 0x80, 0x86, 0xcf, 0x8b, 0xcb, 0x5b,
	0x79, 0xe4, 0x3d, 0x6c, 0xd8, 0x82, 0x4e, 0x35, 0x59, 0x54, 0xad, 0xc7, 0xa6, 0x64, 0x49, 0x20,
	0x1c, 0x66, 0x5e, 0x2a, 0x02, 0x57, 0xd2, 0x5a, 0x47, 0x4e, 0xa0, 0x13, 0x71, 0xc9, 0x8a, 0x31,
	0x85, 0x46, 0x69, 0xd6, 0xae, 0xf9, 0x67, 0x0b, 0xf3, 0x52, 0x71, 0xb4, 0x56, 0x91, 0x97, 0x1b,
	0x5e, 0xfa, 0xa6, 0x73, 0xdf, 0x71, 0xe3, 0x47, 0x03, 0x3a, 0x55, 0x35, 0x72, 0x04, 0x7a, 0x26,
	0xf2, 0xd4, 0x29, 0x9e, 0x78, 0x14, 0x05, 0x52, 0x35, 0xd1, 0x2b, 0xc1, 0x19, 0x62, 0x64, 0x06,
	0x3b, 0x98, 0x39, 0xbb, 0x1e, 0x87, 0xaa, 0xab, 0xc1, 0xbd, 0x0c, 0x5f, 0x55, 0x0a, 0xda, 0xc7,
	0x25, 0xf5, 0x3f, 0x39, 0x86, 0x6d, 0xc9, 0x52, 0x9f, 0x4b, 0xec, 0xae, 0x6f, 0xed, 0xd4, 0x8e,
	0x5c, 0x21, 0x4c, 0x15, 0x3d, 0xd2, 0xa0, 0x3b, 0x2d, 0x86, 0xc0, 0x45, 0xec, 0x89, 0x29, 0x7c,
	0xee, 0x54, 0xc3, 0xfa, 0x77, 0x00, 0x00, 0x00, 0xff, 0xff, 0xb0, 0xe3, 0xa3, 0x35, 0xcc, 0x05,
	0x00, 0x00,
}
