// Code generated by protoc-gen-go. DO NOT EDIT.
// source: pkg/proto/manifest.proto

package proto

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// Values are 16-bit integers:
//    Top byte is an identifier for a family of targets.
//    Bottom byte is a specific target type within that family.
//    Supports 256 targets within a target family.
type Target int32

const (
	// Windows family ID: 0x0100
	Target_Windows_x64      Target = 257
	Target_Windows_x86      Target = 258
	Target_Windows_AppStore Target = 259
	// MacOS family ID: 0x0100
	Target_MacOS_Universal Target = 513
	// Linux family ID: 0x0300
	Target_Linux_Universal Target = 769
	Target_Linux_x64       Target = 770
	// Apple platform family ID: 0x0400
	Target_Apple_iOS  Target = 1025
	Target_Apple_tvOS Target = 1026
	// Android family ID: 0x0500
	Target_Andooid Target = 1281
	// WebGL family ID: 0x0600
	Target_WebGL Target = 1537
	// Sony Console family ID: 0x0700
	Target_PS4     Target = 1793
	Target_PS_Vita Target = 1794
	// Microsoft console family ID: 0x0800
	Target_XboxOne Target = 2049
	// Nintendo console family ID: 0x0900
	Target_Nintendo_Switch Target = 2305
	Target_Nintendo_3DS    Target = 2306
)

var Target_name = map[int32]string{
	257:  "Windows_x64",
	258:  "Windows_x86",
	259:  "Windows_AppStore",
	513:  "MacOS_Universal",
	769:  "Linux_Universal",
	770:  "Linux_x64",
	1025: "Apple_iOS",
	1026: "Apple_tvOS",
	1281: "Andooid",
	1537: "WebGL",
	1793: "PS4",
	1794: "PS_Vita",
	2049: "XboxOne",
	2305: "Nintendo_Switch",
	2306: "Nintendo_3DS",
}

var Target_value = map[string]int32{
	"Windows_x64":      257,
	"Windows_x86":      258,
	"Windows_AppStore": 259,
	"MacOS_Universal":  513,
	"Linux_Universal":  769,
	"Linux_x64":        770,
	"Apple_iOS":        1025,
	"Apple_tvOS":       1026,
	"Andooid":          1281,
	"WebGL":            1537,
	"PS4":              1793,
	"PS_Vita":          1794,
	"XboxOne":          2049,
	"Nintendo_Switch":  2305,
	"Nintendo_3DS":     2306,
}

func (x Target) Enum() *Target {
	p := new(Target)
	*p = x
	return p
}

func (x Target) String() string {
	return proto.EnumName(Target_name, int32(x))
}

func (x *Target) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(Target_value, data, "Target")
	if err != nil {
		return err
	}
	*x = Target(value)
	return nil
}

func (Target) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_fad21e446ead9c15, []int{0}
}

type TargetSet struct {
	Targets              []Target `protobuf:"varint,1,rep,name=targets,enum=tapioca.Target" json:"targets,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TargetSet) Reset()         { *m = TargetSet{} }
func (m *TargetSet) String() string { return proto.CompactTextString(m) }
func (*TargetSet) ProtoMessage()    {}
func (*TargetSet) Descriptor() ([]byte, []int) {
	return fileDescriptor_fad21e446ead9c15, []int{0}
}

func (m *TargetSet) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TargetSet.Unmarshal(m, b)
}
func (m *TargetSet) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TargetSet.Marshal(b, m, deterministic)
}
func (m *TargetSet) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TargetSet.Merge(m, src)
}
func (m *TargetSet) XXX_Size() int {
	return xxx_messageInfo_TargetSet.Size(m)
}
func (m *TargetSet) XXX_DiscardUnknown() {
	xxx_messageInfo_TargetSet.DiscardUnknown(m)
}

var xxx_messageInfo_TargetSet proto.InternalMessageInfo

func (m *TargetSet) GetTargets() []Target {
	if m != nil {
		return m.Targets
	}
	return nil
}

type ManifestProto struct {
	Blocks               []*ManifestBlockProto         `protobuf:"bytes,1,rep,name=blocks" json:"blocks,omitempty"`
	Items                map[string]*ManifestItemProto `protobuf:"bytes,2,rep,name=items" json:"items,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Metadata             *ManifestMetadataProto        `protobuf:"bytes,3,opt,name=metadata" json:"metadata,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                      `json:"-"`
	XXX_unrecognized     []byte                        `json:"-"`
	XXX_sizecache        int32                         `json:"-"`
}

func (m *ManifestProto) Reset()         { *m = ManifestProto{} }
func (m *ManifestProto) String() string { return proto.CompactTextString(m) }
func (*ManifestProto) ProtoMessage()    {}
func (*ManifestProto) Descriptor() ([]byte, []int) {
	return fileDescriptor_fad21e446ead9c15, []int{1}
}

func (m *ManifestProto) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ManifestProto.Unmarshal(m, b)
}
func (m *ManifestProto) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ManifestProto.Marshal(b, m, deterministic)
}
func (m *ManifestProto) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ManifestProto.Merge(m, src)
}
func (m *ManifestProto) XXX_Size() int {
	return xxx_messageInfo_ManifestProto.Size(m)
}
func (m *ManifestProto) XXX_DiscardUnknown() {
	xxx_messageInfo_ManifestProto.DiscardUnknown(m)
}

var xxx_messageInfo_ManifestProto proto.InternalMessageInfo

func (m *ManifestProto) GetBlocks() []*ManifestBlockProto {
	if m != nil {
		return m.Blocks
	}
	return nil
}

func (m *ManifestProto) GetItems() map[string]*ManifestItemProto {
	if m != nil {
		return m.Items
	}
	return nil
}

func (m *ManifestProto) GetMetadata() *ManifestMetadataProto {
	if m != nil {
		return m.Metadata
	}
	return nil
}

type ManifestMetadataProto struct {
	// The targets the build is valid on.
	Targets []Target `protobuf:"varint,1,rep,name=targets,enum=tapioca.Target" json:"targets,omitempty"`
	// Required: the maximum size of blocks within the build in bytes.
	MaxBlockSize         *uint64  `protobuf:"varint,2,opt,name=max_block_size,json=maxBlockSize,def=1048576" json:"max_block_size,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ManifestMetadataProto) Reset()         { *m = ManifestMetadataProto{} }
func (m *ManifestMetadataProto) String() string { return proto.CompactTextString(m) }
func (*ManifestMetadataProto) ProtoMessage()    {}
func (*ManifestMetadataProto) Descriptor() ([]byte, []int) {
	return fileDescriptor_fad21e446ead9c15, []int{2}
}

func (m *ManifestMetadataProto) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ManifestMetadataProto.Unmarshal(m, b)
}
func (m *ManifestMetadataProto) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ManifestMetadataProto.Marshal(b, m, deterministic)
}
func (m *ManifestMetadataProto) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ManifestMetadataProto.Merge(m, src)
}
func (m *ManifestMetadataProto) XXX_Size() int {
	return xxx_messageInfo_ManifestMetadataProto.Size(m)
}
func (m *ManifestMetadataProto) XXX_DiscardUnknown() {
	xxx_messageInfo_ManifestMetadataProto.DiscardUnknown(m)
}

var xxx_messageInfo_ManifestMetadataProto proto.InternalMessageInfo

const Default_ManifestMetadataProto_MaxBlockSize uint64 = 1048576

func (m *ManifestMetadataProto) GetTargets() []Target {
	if m != nil {
		return m.Targets
	}
	return nil
}

func (m *ManifestMetadataProto) GetMaxBlockSize() uint64 {
	if m != nil && m.MaxBlockSize != nil {
		return *m.MaxBlockSize
	}
	return Default_ManifestMetadataProto_MaxBlockSize
}

// A manifest descriptor for a block within a build
type ManifestBlockProto struct {
	// The hash of the block
	Hash []byte `protobuf:"bytes,1,opt,name=hash" json:"hash,omitempty"`
	// Optional: The size of the block. Only present when the size of the block is
	// not the max_block_size of the manifest.
	Size                 *uint64  `protobuf:"varint,2,opt,name=size,def=1048576" json:"size,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ManifestBlockProto) Reset()         { *m = ManifestBlockProto{} }
func (m *ManifestBlockProto) String() string { return proto.CompactTextString(m) }
func (*ManifestBlockProto) ProtoMessage()    {}
func (*ManifestBlockProto) Descriptor() ([]byte, []int) {
	return fileDescriptor_fad21e446ead9c15, []int{3}
}

func (m *ManifestBlockProto) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ManifestBlockProto.Unmarshal(m, b)
}
func (m *ManifestBlockProto) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ManifestBlockProto.Marshal(b, m, deterministic)
}
func (m *ManifestBlockProto) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ManifestBlockProto.Merge(m, src)
}
func (m *ManifestBlockProto) XXX_Size() int {
	return xxx_messageInfo_ManifestBlockProto.Size(m)
}
func (m *ManifestBlockProto) XXX_DiscardUnknown() {
	xxx_messageInfo_ManifestBlockProto.DiscardUnknown(m)
}

var xxx_messageInfo_ManifestBlockProto proto.InternalMessageInfo

const Default_ManifestBlockProto_Size uint64 = 1048576

func (m *ManifestBlockProto) GetHash() []byte {
	if m != nil {
		return m.Hash
	}
	return nil
}

func (m *ManifestBlockProto) GetSize() uint64 {
	if m != nil && m.Size != nil {
		return *m.Size
	}
	return Default_ManifestBlockProto_Size
}

// A manifest descriptor for a item (a file or directory) within a build
type ManifestItemProto struct {
	// File only. The sequence of block ranges that consitute the file.
	Blocks []*ManifestBlockRange `protobuf:"bytes,1,rep,name=blocks" json:"blocks,omitempty"`
	// Directory only. All child nodes within the directory.
	Children             map[string]*ManifestItemProto `protobuf:"bytes,2,rep,name=children" json:"children,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	XXX_NoUnkeyedLiteral struct{}                      `json:"-"`
	XXX_unrecognized     []byte                        `json:"-"`
	XXX_sizecache        int32                         `json:"-"`
}

func (m *ManifestItemProto) Reset()         { *m = ManifestItemProto{} }
func (m *ManifestItemProto) String() string { return proto.CompactTextString(m) }
func (*ManifestItemProto) ProtoMessage()    {}
func (*ManifestItemProto) Descriptor() ([]byte, []int) {
	return fileDescriptor_fad21e446ead9c15, []int{4}
}

func (m *ManifestItemProto) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ManifestItemProto.Unmarshal(m, b)
}
func (m *ManifestItemProto) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ManifestItemProto.Marshal(b, m, deterministic)
}
func (m *ManifestItemProto) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ManifestItemProto.Merge(m, src)
}
func (m *ManifestItemProto) XXX_Size() int {
	return xxx_messageInfo_ManifestItemProto.Size(m)
}
func (m *ManifestItemProto) XXX_DiscardUnknown() {
	xxx_messageInfo_ManifestItemProto.DiscardUnknown(m)
}

var xxx_messageInfo_ManifestItemProto proto.InternalMessageInfo

func (m *ManifestItemProto) GetBlocks() []*ManifestBlockRange {
	if m != nil {
		return m.Blocks
	}
	return nil
}

func (m *ManifestItemProto) GetChildren() map[string]*ManifestItemProto {
	if m != nil {
		return m.Children
	}
	return nil
}

type ManifestBlockRange struct {
	// The first block in the range. This is the index of the first block in the
	// range.
	StartId *uint64 `protobuf:"varint,1,opt,name=start_id,json=startId" json:"start_id,omitempty"`
	// The number of blocks in the range.
	Size                 *uint64  `protobuf:"varint,2,opt,name=size,def=1" json:"size,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ManifestBlockRange) Reset()         { *m = ManifestBlockRange{} }
func (m *ManifestBlockRange) String() string { return proto.CompactTextString(m) }
func (*ManifestBlockRange) ProtoMessage()    {}
func (*ManifestBlockRange) Descriptor() ([]byte, []int) {
	return fileDescriptor_fad21e446ead9c15, []int{5}
}

func (m *ManifestBlockRange) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ManifestBlockRange.Unmarshal(m, b)
}
func (m *ManifestBlockRange) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ManifestBlockRange.Marshal(b, m, deterministic)
}
func (m *ManifestBlockRange) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ManifestBlockRange.Merge(m, src)
}
func (m *ManifestBlockRange) XXX_Size() int {
	return xxx_messageInfo_ManifestBlockRange.Size(m)
}
func (m *ManifestBlockRange) XXX_DiscardUnknown() {
	xxx_messageInfo_ManifestBlockRange.DiscardUnknown(m)
}

var xxx_messageInfo_ManifestBlockRange proto.InternalMessageInfo

const Default_ManifestBlockRange_Size uint64 = 1

func (m *ManifestBlockRange) GetStartId() uint64 {
	if m != nil && m.StartId != nil {
		return *m.StartId
	}
	return 0
}

func (m *ManifestBlockRange) GetSize() uint64 {
	if m != nil && m.Size != nil {
		return *m.Size
	}
	return Default_ManifestBlockRange_Size
}

func init() {
	proto.RegisterEnum("tapioca.Target", Target_name, Target_value)
	proto.RegisterType((*TargetSet)(nil), "tapioca.TargetSet")
	proto.RegisterType((*ManifestProto)(nil), "tapioca.ManifestProto")
	proto.RegisterMapType((map[string]*ManifestItemProto)(nil), "tapioca.ManifestProto.ItemsEntry")
	proto.RegisterType((*ManifestMetadataProto)(nil), "tapioca.ManifestMetadataProto")
	proto.RegisterType((*ManifestBlockProto)(nil), "tapioca.ManifestBlockProto")
	proto.RegisterType((*ManifestItemProto)(nil), "tapioca.ManifestItemProto")
	proto.RegisterMapType((map[string]*ManifestItemProto)(nil), "tapioca.ManifestItemProto.ChildrenEntry")
	proto.RegisterType((*ManifestBlockRange)(nil), "tapioca.ManifestBlockRange")
}

func init() { proto.RegisterFile("pkg/proto/manifest.proto", fileDescriptor_fad21e446ead9c15) }

var fileDescriptor_fad21e446ead9c15 = []byte{
	// 570 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x94, 0x4f, 0x6f, 0xd3, 0x40,
	0x10, 0xc5, 0x65, 0x27, 0x6d, 0x9c, 0x49, 0x9a, 0x6e, 0x47, 0x54, 0x32, 0xad, 0x84, 0x4a, 0x4e,
	0x01, 0x89, 0xf4, 0x2f, 0x69, 0xd5, 0x5b, 0x4b, 0x0b, 0xaa, 0xd4, 0x92, 0xc8, 0x2e, 0x04, 0x71,
	0xb1, 0x36, 0xf1, 0x92, 0xac, 0x92, 0xd8, 0xc6, 0xde, 0xa6, 0x69, 0x6f, 0x0e, 0x27, 0x4e, 0x7c,
	0x4c, 0xbe, 0x06, 0xf2, 0xae, 0x63, 0x08, 0x29, 0x12, 0x48, 0xdc, 0x3c, 0xb3, 0xbf, 0xf7, 0x66,
	0xf7, 0x8d, 0x64, 0x30, 0x83, 0x41, 0x6f, 0x3b, 0x08, 0x7d, 0xe1, 0x6f, 0x8f, 0xa8, 0xc7, 0x3f,
	0xb1, 0x48, 0xd4, 0x65, 0x89, 0x05, 0x41, 0x03, 0xee, 0x77, 0x69, 0xb5, 0x01, 0xc5, 0x6b, 0x1a,
	0xf6, 0x98, 0xb0, 0x99, 0xc0, 0x67, 0x50, 0x10, 0xb2, 0x88, 0x4c, 0x6d, 0x2b, 0x57, 0xab, 0xec,
	0xad, 0xd6, 0x53, 0xae, 0xae, 0x20, 0x6b, 0x76, 0x5e, 0xfd, 0xa6, 0xc3, 0xca, 0x55, 0xea, 0xd9,
	0x92, 0x96, 0xfb, 0xb0, 0xdc, 0x19, 0xfa, 0xdd, 0x81, 0xd2, 0x96, 0xf6, 0x36, 0x33, 0xed, 0x8c,
	0x3b, 0x4d, 0x8e, 0x25, 0x6c, 0xa5, 0x28, 0x1e, 0xc2, 0x12, 0x17, 0x6c, 0x14, 0x99, 0xba, 0xd4,
	0x3c, 0x5d, 0xd0, 0x48, 0xbc, 0x7e, 0x91, 0x30, 0xe7, 0x9e, 0x08, 0xef, 0x2c, 0xc5, 0xe3, 0x31,
	0x18, 0x23, 0x26, 0xa8, 0x4b, 0x05, 0x35, 0x73, 0x5b, 0x5a, 0xad, 0xb4, 0xf7, 0x64, 0x41, 0x7b,
	0x95, 0x02, 0x6a, 0x64, 0xc6, 0x6f, 0x5c, 0x03, 0xfc, 0x34, 0x44, 0x02, 0xb9, 0x01, 0xbb, 0x33,
	0xb5, 0x2d, 0xad, 0x56, 0xb4, 0x92, 0x4f, 0xdc, 0x81, 0xa5, 0x31, 0x1d, 0xde, 0x30, 0x53, 0x97,
	0xc6, 0x1b, 0x0b, 0xc6, 0x89, 0x5a, 0x99, 0x2a, 0xf0, 0x58, 0x3f, 0xd2, 0xaa, 0x9f, 0x61, 0xfd,
	0xc1, 0xc1, 0xff, 0x90, 0x2a, 0xbe, 0x80, 0xca, 0x88, 0x4e, 0x1c, 0x19, 0x8e, 0x13, 0xf1, 0x7b,
	0x75, 0x85, 0xfc, 0x71, 0x61, 0x77, 0xe7, 0xe0, 0xe8, 0xe5, 0x61, 0xc3, 0x2a, 0x8f, 0xe8, 0x44,
	0xc6, 0x68, 0xf3, 0x7b, 0x56, 0x3d, 0x07, 0x5c, 0xcc, 0x16, 0x11, 0xf2, 0x7d, 0x1a, 0xf5, 0xe5,
	0x8b, 0xca, 0x96, 0xfc, 0xc6, 0x4d, 0xc8, 0x3f, 0x64, 0x27, 0x9b, 0xd5, 0xef, 0x1a, 0xac, 0x2d,
	0x3c, 0xed, 0x6f, 0xf7, 0x69, 0x51, 0xaf, 0xc7, 0xb2, 0x7d, 0x9e, 0x81, 0xd1, 0xed, 0xf3, 0xa1,
	0x1b, 0x32, 0x2f, 0x5d, 0x69, 0xed, 0xcf, 0xe9, 0xd5, 0x5f, 0xa5, 0xa8, 0xda, 0x6c, 0xa6, 0xdc,
	0x68, 0xc3, 0xca, 0xdc, 0xd1, 0x7f, 0xdb, 0xd1, 0xeb, 0xdf, 0x02, 0x93, 0x97, 0xc7, 0xc7, 0x60,
	0x44, 0x82, 0x86, 0xc2, 0xe1, 0xae, 0x1c, 0x91, 0xb7, 0x0a, 0xb2, 0xbe, 0x70, 0x71, 0x7d, 0x2e,
	0x37, 0x6d, 0x57, 0x25, 0xf6, 0xfc, 0xab, 0x0e, 0xcb, 0x6a, 0x77, 0x48, 0xa0, 0xd4, 0xe6, 0x9e,
	0xeb, 0xdf, 0x46, 0xce, 0xa4, 0x71, 0x40, 0x62, 0x7d, 0xae, 0x73, 0xd4, 0x20, 0x53, 0x1d, 0xd7,
	0x81, 0xcc, 0x3a, 0x27, 0x41, 0x60, 0x0b, 0x3f, 0x64, 0xe4, 0x8b, 0x8e, 0x8f, 0x60, 0xf5, 0x8a,
	0x76, 0x9b, 0xb6, 0xf3, 0xce, 0xe3, 0x63, 0x16, 0x46, 0x74, 0x48, 0xe2, 0x7c, 0xd2, 0xbd, 0xe4,
	0xde, 0xcd, 0xe4, 0xd7, 0xee, 0x32, 0x56, 0xa0, 0xa8, 0xba, 0xc9, 0x90, 0xa9, 0xac, 0x4f, 0x82,
	0x60, 0xc8, 0x1c, 0xde, 0xb4, 0x49, 0x6c, 0xe0, 0x2a, 0x80, 0xaa, 0xc5, 0xb8, 0x69, 0x93, 0xa9,
	0x81, 0x65, 0x28, 0x9c, 0x78, 0xae, 0xef, 0x73, 0x97, 0xc4, 0x80, 0x00, 0x4b, 0x6d, 0xd6, 0x79,
	0x73, 0x49, 0xe2, 0x32, 0x1a, 0x90, 0x6b, 0xd9, 0x07, 0x24, 0xae, 0x24, 0x4c, 0xcb, 0x76, 0xde,
	0x73, 0x41, 0xc9, 0x54, 0x56, 0x1f, 0x3a, 0xfe, 0xa4, 0xe9, 0x31, 0x12, 0x93, 0xe4, 0x1a, 0x6f,
	0xb9, 0x27, 0x98, 0xe7, 0xfa, 0x8e, 0x7d, 0xcb, 0x45, 0xb7, 0x4f, 0x62, 0xc4, 0x35, 0x28, 0x67,
	0xdd, 0xfd, 0x33, 0x9b, 0x4c, 0xf1, 0xb4, 0xf4, 0xb1, 0x98, 0xfd, 0x66, 0x7e, 0x04, 0x00, 0x00,
	0xff, 0xff, 0x73, 0x87, 0x09, 0xe6, 0x72, 0x04, 0x00, 0x00,
}
